### ISSUE TITLE
服务端npm i 后报错

### ISSUE THREAD

**Issue by xubillde** [houxiaozhao/template#1]
Module '"mongoose"' has no exported member 'Types'.

应该是mongoose版本吧，但是没动package.json内的版本

**Comment by houxiaozhao** [comment]
@LDXu 使用yarn 重新安装mongoose 和 @typegoose/typegoose 即可
或者更新到最新版本
然后把代码中的`Types.ObjectId `改为 `new Types.ObjectId`
mongo数据库链接的options有些弃用了,删掉就没有警告了.
![image](https://user-images.githubusercontent.com/14978325/135415737-dbe904bf-e37d-4473-8beb-478a3cad02e8.png)
😀

**Comment by houxiaozhao** [comment]
更新后的版本已经提交了 : )

**Comment by xubillde** [comment]
可以了，按readme.md 尝试了admin配置账户，web使用，不错的。了解了整个项目的思路。
有一处可能未完善：
添加用户后无法编辑更新权限了。
还有一处可优化：
菜单配置的菜单图标，默认加一个，或者支持一下文件上传。这样的话可能会加快开发速度。
